version: "3.9"
services:
  couchbase1:
    container_name: couchbase1
    image: couchbase/server
    volumes:
      - type: volume
        source: couchbase1
        target: /opt/couchbase1/var
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.11
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    ulimits:
      nproc: 65535
      core:
        soft: 100000000
        hard: 100000000
      memlock:
        soft: 100000000
        hard: 100000000
      nofile:
        soft: 40960
        hard: 40960
  couchbase2:
    container_name: couchbase2
    image: couchbase/server
    volumes:
      - type: volume
        source: couchbase2
        target: /opt/couchbase2/var
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.12
    links:
      - couchbase1
    depends_on:
      - couchbase1
    ports:
      - 18091:8091
      - 18092:8092
      - 18093:8093
      - 18094:8094
      - 21210:11210
  couchbase3:
    container_name: couchbase3
    image: couchbase/server
    volumes:
      - type: volume
        source: couchbase3
        target: /opt/couchbase3/var
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.13
    links:
      - couchbase2
    depends_on:
      - couchbase2
    ports:
      - 28091:8091
      - 28092:8092
      - 28093:8093
      - 28094:8094
      - 31210:11210
    ulimits:
      nproc: 65535
      core:
        soft: 100000000
        hard: 100000000
      memlock:
        soft: 100000000
        hard: 100000000
      nofile:
        soft: 40960
        hard: 40960

  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    expose:
      - "8500"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    networks: 
      couchbase-net:
        ipv4_address: 172.16.101.17


  gateway:
    depends_on:
      - blog-api
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile-API-Gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:5001
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.15
    ports:
      - "5001:5001"
    expose:
      - "5001"
    links:
      - consul

  blog-api:
    depends_on:
      - consul
      - couchbase1
      - couchbase2
      - couchbase3
    image: blog-api
    build:
      context: .
      dockerfile: Dockerfile-Blog-API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:5011
    networks:
      couchbase-net:
        ipv4_address: 172.16.101.16
    ports:
      - "5011:5011"
    expose:
      - "5011"

networks:
  couchbase-net:
    name: couchbase-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.101.0/24
volumes:
  couchbase1:
  couchbase2:
  couchbase3: