FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
EXPOSE 5001:5001
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY API-Gateway/API-Gateway.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY API-Gateway/ .
RUN dotnet publish -c Release -o /app/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "api_gateway.dll"]